### ISSUE TITLE
Execute Balea only in the specified authentication schemes

### ISSUE THREAD

**Issue by hbiarge** [Xabaril/Balea#12]
Right now, if you configure Balea in an application the middleware is executed for all authentication schemes defined in the application. It will be the main use case.

But in some applications where you register more than one authentication scheme, it would be nice to be able to configure Balea to run only in some of those authentication schemes.

For example when you have an Api and a Mvc web application both running in the same host and each one with their authentication scheme configured (Jwt and Cookies)

**Comment by lurumad** [comment]
Hi @hbiarge 

PR is welcome.
