### ISSUE TITLE
Support many SubjectClaimTypes

### ISSUE THREAD

**Issue by unaizorrilla** [Xabaril/Balea#25]
At this moment, Balea allow to specify the SubjectClaimType and FallbackClaimType to create the map between the principal and configured user in Balea store.

In some cases, this two options are not enought to satisfy some application requirements. There is one scenario:

 - Identity Server with many Identity providers ( local and ad )
 - HTTP API app secured with the identity server
  - some methods can be invoked with users from local and from ad and also with client credentials

Will be interesting to support a list of allowed subject claim types instead a simple subject / fallback

What do you think about this?

**Comment by lurumad** [comment]
Hi @unaizorrilla 

PRs are welcome!

**Comment by lurumad** [comment]
Thanks @unaizorrilla for your contribution!
