### ISSUE TITLE
If model not valid, return view and display the error

### ISSUE THREAD

**Issue by miguelEsteban** [Xabaril/Balea#35]
**Source: sample/ContosoUniversity.Configuration.Store/Controllers/AccountController.cs**
In the login view jquery validate unobtrusive is broken because can´t load .datepicker jquery plugin , this cause a server exception if you try to login without user (that is requiered in the view mnodel).
Cheers

**Comment by lurumad** [comment]
Thanks @miguelEsteban 

It will be fixed in the .NET 5.0 release.

Regards!
