### ISSUE TITLE
Blazor WASM - There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.

### ISSUE THREAD

**Issue by jkears** [Xabaril/Balea#46]
When adding the Balea to a Blazor WASM we get the following error...

There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.

**Comment by jkears** [comment]
Thanks we were able to get this working.

**Comment by Seix** [comment]
I have the same problem with a new project. Eventually all nuget package references show warning icon...
Any suggestions? 
What workerd for you?
![image](https://user-images.githubusercontent.com/1552898/193811257-420a0576-0718-4e70-afcc-1def9c18bf9b.png)
